version: 0.2

phases:
  install:
    runtime-versions:
      docker : 19
  pre_build:
    commands:
      - echo Current Build number is v${CODEBUILD_BUILD_NUMBER}
      - echo Loggin in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t bookapp:v${CODEBUILD_BUILD_NUMBER} .
      - docker tag bookapp:v${CODEBUILD_BUILD_NUMBER} ${ECR_REPOSITORY_URI}:v${CODEBUILD_BUILD_NUMBER}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY_URI}:v${CODEBUILD_BUILD_NUMBER}
      - echo Writing image definitions file...
      - printf '[{"name":"book-container","imageUri":"%s"}]' ${ECR_REPOSITORY_URI}:v${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    #cache:
    #paths:
    # - paths