spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/book
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

feign:
  client:
    config:
      default:
        connectTimout: 100
        readTimeout: 1000
        loggerLevel: HEADERS
  composite-api:
    url: https://www.cloudlibrary.shop/v1

logging:
  level: debug
---
spring:
  application:
    name: book-sample-local
  config:
    activate:
      on-profile: local

---
spring:
  application:
    name: book-sample-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: book-sample-prod
  config:
    activate:
      on-profile: prod