spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://book-db.cscg6f0frodu.us-east-1.rds.amazonaws.com:3306/book
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qwer1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop


feign:
  client:
    config:
      default:
        connectTimout: 100
        readTimeout: 1000
        loggerLevel: HEADERS
  composite-api:
    url: https://www.cloudlibrary.shop/v1
logging:
  level:
    root: info
    com.cloudlibrary.books: debug

---
spring:
  application:
    name: book-sample-local
  config:
    activate:
      on-profile: local

---
spring:
  application:
    name: book-sample-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: book-sample-prod
  config:
    activate:
      on-profile: prod